version: "2"

services:
  beanstalk:
    image: schickling/beanstalkd
    restart: always

  producer:
    image: copierrj/beanstalkdemo_producer
    restart: always
    environment:
      BEANSTALK_HOST: beanstalk
      TIME_TO_RUN: 2
    
  consumer:
    image: copierrj/beanstalkdemo_consumer
    restart: always
    environment:
      BEANSTALK_HOST: beanstalk
      TOUCH_DELAY: 1
      
  console:
    image: agaveapi/beanstalkd-console
    restart: always
    environment:
      BEANSTALKD_HOST: beanstalk
    ports:
      - "80:80"
      - "443:443"