version: "2"

services:
  beanstalk:
    image: schickling/beanstalkd
    restart: always

  producer:
    image: producer
    restart: always
    environment:
      BEANSTALK_HOST: beanstalk
    
  consumer:
    image: consumer
    restart: always
    environment:
      BEANSTALK_HOST: beanstalk
      
  console:
    image: agaveapi/beanstalkd-console
    restart: always
    environment:
      BEANSTALKD_HOST: beanstalk
    ports:
      - "80:80"
      - "443:443"